image: node:15.9.0

pipelines:
  branches:
    master:
      - step:
          name: "Build"
          caches:
            - node
          script:
            - npm install --quiet
            - npm run build --progress=false
          artifacts:
            - dist/escape-rooms-ebooking-front/**
      - step:
          name: "Archive"
          image: alpine:3.13.5
          caches:
            - node
          script:
            - tar -zcvf erb-app.tar.gz dist/escape-rooms-ebooking-front
          artifacts:
            - archives/erb-app.tar.gz
      - parallel:
        - step:
            name: "Test"
            caches:
              - node
            script:
              - npm test
        - step:
            name: "Lint"
            caches:
              - node
            script:
              - npm lint

      - step:
          name: Deploy
          deployment: production
          caches:
            - pip
          script:
            - pipe: atlassian/heroku-deploy:0.1.1
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: $HEROKU_FRONT_APP_NAME
                ZIP_FILE: archives/erb-app.tar.gz
