image: node:15.9.0

pipelines:
  branches:
    master:
      - step:
          name: "Build"
          caches:
            - node
          script:
            - npm install --quiet
            - npm run build --progress=false
            - git archive --format=tar.gz master -o erb-app.tar.gz
          artifacts:
            - erb-app.tar.gz
      - parallel:
        - step:
            name: "Test"
            caches:
              - node
            script:
              - ng test
        - step:
            name: "Lint"
            caches:
              - node
            script:
              - npm lint

      - step:
          name: Deploy
          deployment: production
          caches:
            - pip
          script:
            - pipe: atlassian/heroku-deploy:0.1.1
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: $HEROKU_FRONT_APP_NAME
                ZIP_FILE: erb-app.tar.gz
